# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 512
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  
  (0..1).each do |i|
    config.vm.define "lb-#{i}" do |node|
      node.vm.hostname = "lb-#{i}"
      node.vm.network "private_network", ip: "192.168.100.24#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "lb-#{i}"
      end
    end
  end

end
