# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_check_update = false

  config.vm.hostname = "storage-0"
  config.vm.network "private_network", ip: "192.168.100.230"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 512
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  
end
